language: rust
rust:
- nightly
notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGVyaWtqJTNBamtpLnJlLyUyMXFZdVBFanZyY2htSm5FTHVRbCUzQWpraS5yZQ"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never
